name: CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
            for i in `seq 5`
            do curl --connect-timeout 2 9.9.9.9 2>&1 | grep "curl: (52" || echo non-zero
            sleep 5
            done
