name: CI
on: 
  schedule:
    - cron: '40 2/6 * * *' #every six hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: | #run curl 340 times with 63 second interval (total < six hours), if grep didnt find - send notif.
            exit_56_found=tue
            exit_52_found=true
            for i in `seq 340`
            do
              result1=$(curl --connect-timeout 15 ${{ secrets.DOMAIN2 }}:443 2>&1 | grep "curl: (56" || 1>&0)
              result2=$(curl --connect-timeout 15 ${{ secrets.DOMAIN }}:443 2>&1 | grep "curl: (52" || 1>&0)
              # if exit code 56 not found and flag not set
              if [ ! -z "$result1" ] && [ "$exit_56_found" = false ]; then
                exit_56_found=true
              # notify that host becomes up after it was down
                curl -s -X POST "https://api.telegram.org/bot"${{ secrets.TGBOTKEY }}"/sendMessage" \
                -F chat_id=${{ secrets.CHATID }} -F text="${{ secrets.DOMAIN2 }} is up" 2>/dev/null 1>/dev/null
              fi
              if [ ! -z "$result2" ] && [ "$exit_52_found" = false ]; then
                exit_52_found=true
                curl -s -X POST "https://api.telegram.org/bot"${{ secrets.TGBOTKEY }}"/sendMessage" \
                -F chat_id=${{ secrets.CHATID }} -F text="${{ secrets.DOMAIN }} is up" 2>/dev/null 1>/dev/null
              fi
              # if exit code 56 was found and flag set
              if [ -z "$result1" ] && [ "$exit_56_found" = true ]; then
                exit_56_found=false
              # notify that host goes down
                curl -s -X POST "https://api.telegram.org/bot"${{ secrets.TGBOTKEY }}"/sendMessage" \
                -F chat_id=${{ secrets.CHATID }} -F text="${{ secrets.DOMAIN2 }} is down" 2>/dev/null 1>/dev/null
              fi
              if [ -z "$result2" ] && [ "$exit_52_found" = true ]; then
                exit_52_found=false
                curl -s -X POST "https://api.telegram.org/bot"${{ secrets.TGBOTKEY }}"/sendMessage" \
                -F chat_id=${{ secrets.CHATID }} -F text="${{ secrets.DOMAIN }} is down" 2>/dev/null 1>/dev/null
              fi
              sleep 63
              done
