name: CI
on: 
  schedule:
    - cron: '40 2/6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
            _56=1
            _52=1
            n=/dev/null
            tg="curl -s -X POST "https://api.telegram.org/bot"${{ secrets.TGBOTKEY }}"/sendMessage" -F chat_id=${{ secrets.CHATID }} -F text="
            for i in `seq 353`
            do
              r1=$(curl --connect-timeout 20 ${{ secrets.DOMAIN2 }}:443 2>&1 | grep "curl: (56" || 1>&0)
              r2=$(curl --connect-timeout 20 ${{ secrets.DOMAIN }}:443 2>&1 | grep "curl: (52" || 1>&0)
              if [ ! -z "$r1" ] && [ "$_56" = 0 ]; then
                _56=1
                $tg"${{ secrets.DOMAIN2 }} is up" &>$n
              fi
              if [ ! -z "$r2" ] && [ "$_52" = 0 ]; then
                _52=1
                $tg"${{ secrets.DOMAIN }} is up" &>$n
              fi
              if [ -z "$r1" ] && [ "$_56" = 1 ]; then
                _56=0
                $tg"${{ secrets.DOMAIN2 }} is down" &>$n
              fi
              if [ -z "$r2" ] && [ "$_52" = 1 ]; then
                _52=0
                $tg"${{ secrets.DOMAIN }} is down" &>$n
              fi
              sleep 60
              done
