name: CI-2
on: 
  schedule:
    - cron: '*/5 * * * *' #test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
            for i in `seq 5`
            do curl --connect-timeout 10 ${{ secrets.DOMAIN }}:443 2>&1 | grep "curl: (52" ||\
            echo "Service monitored by Github is down!" 2>/dev/null 1>/dev/null
            sleep 60
            done
