name: CI
on: 
  schedule:
    - cron: '40 2/6 * * *' #every six hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: | #run curl 356 times with 60 seconds interval (total < six hours), if grep didnt find - send notif.
counter=0

exit_56_found=false

while true; do
  sleep 60

  ((counter++))

  if [ $counter -gt 356 ]; then
    break
  fi
  echo ok
done
