name: CI
on: 
  schedule:
    - cron: '40 2/6 * * *' #every six hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          counter=0
          while true; do
            sleep 60
            #((counter++))
            if [ $counter -gt 356 ]; then
              break
            fi
            echo ok
          done
